
OBJS = parser.cmo scanner.cmo arg.cmo
PROG = helloworld

all: $(PROG) model

model: model.c
	gcc -o model model.c

$(PROG): arg helloworld.arg
	./arg $(PROG)
	gcc -o $(PROG) $(PROG).c

arg : $(OBJS)
	ocamlc str.cma -o arg $(OBJS)

scanner.ml : scanner.mll
	ocamllex scanner.mll

parser.ml parser.mli : parser.mly
	ocamlyacc parser.mly

%.cmo : %.ml
	ocamlc -c $<

%.cmi : %.mli
	ocamlc -c $<


.PHONY : clean
clean :
	rm -f arg parser.ml parser.mli scanner.ml *.cmo *.cmi $(PROG) $(PROG).c model

# Generated by ocamldep *.ml *.mli
arg.cmo: scanner.cmo parser.cmi ast.cmi
arg.cmx: scanner.cmx parser.cmx ast.cmi
parser.cmo: ast.cmi parser.cmi
parser.cmx: ast.cmi parser.cmi
scanner.cmo: parser.cmi
scanner.cmx: parser.cmx
parser.cmi: ast.cmi
